_BASE_: "Base-RCNN-MobileNet-FPN.yaml"
MODEL:
  WEIGHTS: "https://www.dropbox.com/s/yduxbc13s3ip6qn/mobilenet_v2_detectron2.pth?dl=1"
  MASK_ON: False
  FPN:
    OUT_CHANNELS: 128
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "checkpoints/FRCN-MNv2-FPNLite-3x"